### PR TITLE
fix(zeebe-plugin): forward emit to deploy and start-instance overlays

### LINKED ISSUE #6151: Camunda 8 deployment / run tool is broken
### Describe the bug

Deploy / run tool is broken with `v5.51.0-rc.1` - yields an error in the developer console:

```
DeploymentPluginOverlay.js:139 Uncaught (in promise) TypeError: A is not a function
    at xl.e (DeploymentPluginOverlay.js:139:9)
    at i.emit (events.js:153:1)
    at xl.deploy (Deployment.js:151:10)
    at async onSubmit (DeploymentPluginOverlay.js:117:11)
```

### Steps to reproduce

1. Create simple C8 process (start -> end)
2. Trigger deployment tool 
3. **nothing happens**
4. Trigger run tool
5. **nothing happens**

Observe above log.

### Expected behavior

Both tools work. Note that task testing tool *does work*.

### Environment

- OS: Linux
- Camunda Modeler Version: v5.51.0-rc.1
- Execution Platform: Camunda 8
- Installed plug-ins: none

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nikku**
### Proposed Changes

Fixes the broken Camunda 8 **deploy** and **run** tools reported in #6151.

The `DeploymentPluginOverlay` and `StartInstancePluginOverlay` were migrated in [#6106](https://github.com/camunda/camunda-modeler/pull/6106) to emit application events through a new `emit(type, payload)` prop (threaded to plug-ins by `PluginsRoot`). However, the two wrapper plug-ins (`DeploymentPlugin`, `StartInstancePlugin`) were never updated to forward `emit` down to their overlays.

As a result, `emit` was `undefined` inside the overlays. On a successful deploy the `deployment.on('deployed', …)` handler called `emit('deployment.done', …)`, throwing:

```
TypeError: A is not a function
    at DeploymentPluginOverlay.js:139
    at Deployment.deploy (Deployment.js:151)
    at async onSubmit (DeploymentPluginOverlay.js:117)
```

The deploy itself succeeded on the backend, but the post-deploy event emission crashed — so the UI appeared to do nothing. Task testing was unaffected because it lives in a tab that receives `emit` directly.

**Changes**
* Forward `emit` from `DeploymentPlugin` → `DeploymentPluginOverlay`.
* Forward `emit` from `StartInstancePlugin` → `StartInstancePluginOverlay`.
* Add wrapper-level regression tests exercising the deploy → `emit` path (the existing overlay specs passed `emit` directly, so the wrapper gap was uncovered).

### Steps to try out

1. Create a simple C8 process (start → end).
2. Trigger the deployment tool → deploys and shows a success notification.
3. Trigger the run tool → starts an instance.

### Checklist

Ensure you provide everything we need to review your contribution:

* [x] Contribution __meets our [definition of done](https://github.com/bpmn-io/.github/blob/main/resources/DEFINITION_OF_DONE.md)__
* [x] Pull request __establishes context__
  * [x] __Link to related issue(s)__, i.e. `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`
  * [x] __Brief textual description__ of the changes
  * [ ] __Screenshots or short videos__ showing UI/UX changes
  * [x] __Steps to try out__, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)

Closes #6151

### CODE REVIEW

File: client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstancePluginSpec.js [hunk 1]
```diff
@@ -151,6 +151,72 @@ describe('StartInstancePlugin', function() {
...
+      emit,
+      _getGlobal: (name) => {
+        if (name === 'deployment') {
+          return deployment;
+        } else if (name === 'startInstance') {
+          return new StartInstance({
+            async getConnectionForTab() {
+              return {};
+            }
+          });
```
[the remark this answers is not in the document]
Comment (nikku) [reply client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstancePluginSpec.js:193]: Good catch. Fixed — the `StartInstance` mock now stubs `getConfigForFile` (which the overlay calls on mount) instead of `getConnectionForTab`, which was a stray deployment-side method that never matched. I also corrected the same stub in the shared `createStartInstancePlugin` helper, so the existing overlay-render tests no longer trigger the latent `getConfigForFile is not a function` rejection either.
