### ISSUE TITLE
camunda-modeler-linter-plugin does not work with Modeler 5.3.0

### ISSUE THREAD

**Issue by pierre-yves-monnet** [camunda/camunda-modeler#3137]
Hello,
I copied all the plugins I have from Modeler 5.2 to 5.3, and I received this error.

Thie plug in which failed is the linter:
camunda-modeler-property-info-plugin-master](https://github.com/camunda/camunda-modeler-linter-plugin)

```
[D:\dev\intellij\community\zeebe-cherry-framework\src\test\resources\connectorworker\connectorworker.bpmn] this.getModeler(...).get(...).deactivate is not a function
    at deactivate (webpack://camunda-modeler-client/src/app/tabs/cloud-bpmn/BpmnEditor.js:187:39)
    at componentDidUpdate (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:216:295)
    at Vh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:220:181)
    at file:///D:/Camunda/camunda-modeler-5.3.0/resources/app.asar/public/bundle.js:2:803376
    at b (webpack://camunda-modeler-client/node_modules/scheduler/cjs/scheduler.production.min.js:18:162)
    at unstable_runWithPriority (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:250:202)
    at Fi (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:249:382)
    at Di (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:248:143)
    at Yh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:245:331)
    at Xh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:243:85)
    at qf (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:130:227)
    at enqueueSetState (webpack://camunda-modeler-client/node_modules/react/cjs/react.production.min.js:13:223)
    at file:///D:/Camunda/camunda-modeler-5.3.0/resources/app.asar/public/bundle.js:2:2350775 [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
[Disable plug-ins (restarts the app)](https://github.com/camunda/camunda-modeler/issues/new?template=BUG_REPORT.md#) [ info ]
```

**Comment by pinussilvestrus** [comment]
Thanks for reporting! That's probably due to the fact our [built-in linting support](https://github.com/camunda/camunda-modeler/pull/3118) now uses the same bpmn-js extension name (`linting`). 

/cc @philippfromme @christian-konrad, what is our general story on this? Do we encourage using the [linter plugin](https://github.com/camunda/camunda-modeler-linter-plugin) together with the built-in linting?
