### ISSUE TITLE
TypeError when changing expanded sub process to event sub process

### ISSUE THREAD

**Issue by bs11234** [camunda/camunda-modeler#823]
In Camunda Modeler v1.15.1 Windows 64bit: TypeError when changing expanded sub process to event sub process.

The error can be reproduced as follows:

1. Create a BPMN diagram
2. Create DataStoreReference
3. Create another DataStoreReference
4. Create expanded SubProcess
5. Change type of SubProcess to 'Event Sub Process'

The following error occurs:

TypeError: newParent.get is not a function
    at BpmnUpdater.updateSemanticParent (file:///C:/camunda-modeler/resources/app.asar/public/index.js:28555:26)
    at UpdateSemanticParentHandler.execute (file:///C:/camunda-modeler/resources/app.asar/public/index.js:33032:21)
    at file:///C:/camunda-modeler/resources/app.asar/public/index.js:39521:31
    at CommandStack._atomicDo (file:///C:/camunda-modeler/resources/app.asar/public/index.js:39484:5)
    at CommandStack._internalExecute (file:///C:/camunda-modeler/resources/app.asar/public/index.js:39515:8)
    at CommandStack.execute (file:///C:/camunda-modeler/resources/app.asar/public/index.js:39271:8)
    at updateDataStoreParent (file:///C:/camunda-modeler/resources/app.asar/public/index.js:29819:20)
    at Array.forEach (<anonymous>)
    at file:///C:/camunda-modeler/resources/app.asar/public/index.js:29909:10
    at invokeFunction (file:///C:/camunda-modeler/resources/app.asar/public/index.js:41356:13)  [error]

The error seems to occur when you have two DataStoreReference within the diagram. An example diagram is attached.

[TypeError.zip](https://github.com/camunda/camunda-modeler/files/2072816/TypeError.zip)

**Comment by bs11234** [comment]
Works in v1.14.0 on Windows 64bit but not anymore in v1.15.1.

**Comment by nikku** [comment]
Thanks for reporting.

**Comment by philippfromme** [comment]
This is an issue occuring whenever you delete a subprocess in a non-collaboration that contains data stores in the root. In that case we shouldn't attempt to update their parent since this is only necessary in a collaboration.

**Comment by philippfromme** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/commit/5cc28d5d5571287a798b189aed75095f1fd0189e.
